# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Dulles Justice Coalition
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The Dulles Justice Coalition is a nonpartisan alliance of legal non-profits,
  law firms and private individuals. We are working together to uphold democracy
  and justice.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: dullesjustice

collections:
- items

alert: >
  <p>The Ninth Circuit Court of Appeals denied the government's request for an emergency stay, which
  would have reinstated the Executive Order that has prevented refugees and
  people from seven countries from entering the United States.</p>

  <p><strong>Because the Ninth Circuit denied the stay, affected travelers
  can likely enter at least until Monday afternoon.</strong></p>

  <p>Read the <a href="http://s3.documentcloud.org/documents/3452194/9th-Cir-Emergency-Stay-Motion.pdf">motion for immediate stay</a>
    and <a href="http://cdn.ca9.uscourts.gov/datastore/general/2017/02/05/17-35105.pdf">the Ninth Circuit's denial</a></p>

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - circle.yml
  - tools/
  - vendor/
