#!/usr/bin/env bash

set -e

STAGE=$1
PROFILE=${STAGE}
BASE_DIR=./
DIR=$BASE_DIR/_site


if [ "$STAGE" != "test" ] && [ "$STAGE" != "prod" ]; then
  echo "ERROR: Invalid stage: $STAGE"
  exit 1
fi

case "$STAGE" in
 test)
  CLOUDFRONT_DISTRIBUTION_IDS=$TEST_CLOUDFRONT_DISTRIBUTION_IDS
  BUCKET=test.dullesjustice.org
  BUCKET_PATH=""
  ;;
 prod)
  CLOUDFRONT_DISTRIBUTION_IDS=$PROD_CLOUDFRONT_DISTRIBUTION_IDS
  BUCKET=www.dullesjustice.org
  BUCKET_PATH=prod
  ;;
esac

# add AWS profiles
mkdir -p ~/.aws
cat > ~/.aws/credentials <<EOF
[test]
aws_access_key_id=${PROD_ACCESS_KEY}
aws_secret_access_key=${PROD_SECRET_KEY}

[prod]
aws_access_key_id=${PROD_ACCESS_KEY}
aws_secret_access_key=${PROD_SECRET_KEY}
EOF

# deploy
aws s3 rm s3://$BUCKET/$BUCKET_PATH --include "*" --recursive --profile $PROFILE
aws s3 sync $DIR s3://$BUCKET/$BUCKET_PATH --profile $PROFILE

# invalidate CDN cache for index.html
aws configure set preview.cloudfront true

for id in ${CLOUDFRONT_DISTRIBUTION_IDS//,/ }
do
  aws cloudfront create-invalidation --distribution-id $id --paths /* --profile $PROFILE
done
